PROM ubuntu:latest

#Set the Working directory in the image
WORKDIR /app

#copy the files from the host file system to the image file s>
COPY . /app

#Install the necessary packages
RUN apt-get update && apt-get intall -y python3 python3-pip

#Run a command to start the application
CMD ["python3", "app.py"]
